spring.application.name=smart-attendance-system
server.port=2026

#connection properties

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/smartattendance
spring.datasource.username=root
spring.datasource.password=root

#hibernate properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=SmartAttendanceManagementSystemJWTSecretKey2026SuperSecureKey123456789
jwt.expiration=300000

logging.level.org.springframework.security=DEBUG